/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Datos.Privilegios;
import java.awt.Image;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.security.PublicKey;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author beani
 */
public class FrmPrivilegios extends javax.swing.JFrame {

     private Socket servidor;
    private PublicKey serverKey;
    private Object[] claves;
    private String idUser;
    private String email;

    /**
     * Creates new form FrmPrivilegios
     */
    public FrmPrivilegios(Socket servidor, Object[] claves, PublicKey serverKey, String id, String email) throws IOException, ClassNotFoundException {
        initComponents();
        this.servidor = servidor;
        this.claves = claves;
        this.serverKey = serverKey;
        this.idUser = id;
        this.email = email;

        //Centra la ventana en el monitor
        setLocationRelativeTo(null);

        //Icono
        Image imgIcon = new ImageIcon(getClass().getResource("/Imagenes/ico.png")).getImage();
        setIconImage(imgIcon);

        DataOutputStream dos = new DataOutputStream(servidor.getOutputStream());
        dos.writeUTF(email);

        Privilegios p = (Privilegios) Utilidades.Util.recibirObjeto(servidor);

        if (p.getActivar() == 1) {

            jcbActivar.setSelected(true);
        }
        if (p.getAlta() == 1) {

            jcbAlta.setSelected(true);
        }
        if (p.getBaja() == 1) {
            jcbBaja.setSelected(true);
        }
        if (p.getModificar() == 1) {
            jcbMod.setSelected(true);
        }
        if (p.getPrivilegios() == 1) {
            jcbPriv.setSelected(true);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbAlta = new javax.swing.JCheckBox();
        jcbBaja = new javax.swing.JCheckBox();
        jcbActivar = new javax.swing.JCheckBox();
        jcbMod = new javax.swing.JCheckBox();
        jcbPriv = new javax.swing.JCheckBox();
        btnAplicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Cambiar Privilegios");

        jLabel2.setText("Alta Administradores:");

        jLabel3.setText("Baja Usuarios:");

        jLabel4.setText("Activar/Desactivar:");
        jLabel4.setToolTipText("");

        jLabel5.setText("Modificar Usuarios:");

        jLabel6.setText("Cambiar Privilegios:");

        jcbAlta.setText("Alta");

        jcbBaja.setText("Baja");

        jcbActivar.setText("Activar");

        jcbMod.setText("Modificar");

        jcbPriv.setText("Privilegios");

        btnAplicar.setText("Aplicar Cambios");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbPriv)
                            .addComponent(jcbMod)
                            .addComponent(jcbActivar)
                            .addComponent(jcbBaja)
                            .addComponent(jcbAlta)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnAplicar)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbAlta))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbBaja))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbActivar))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbMod))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbPriv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnAplicar)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        // TODO add your handling code here:
        try {
            int activar, alta, baja, cambiar, mod, añadir;
            
            if(jcbActivar.isSelected()){
                activar = 1;
            }else{
                activar = 0;
            }
            
            if(jcbAlta.isSelected()){
                alta = 1;
            }else{
                alta = 0;
            }
            
            
            if(jcbBaja.isSelected()){
                baja = 1;
            }else{
                baja = 0;
            }
            
            if(jcbMod.isSelected()){
                mod = 1;
            }else{
                mod = 0;
            }
            
            if(jcbPriv.isSelected()){
                cambiar = 1;
            }else{
                cambiar = 0;
            }
            
            Privilegios p = new Privilegios(activar, mod,alta, baja, cambiar);
            Utilidades.Util.enviarObject(servidor, p);
            
            this.setVisible(false);
            FrmAdmin f = new FrmAdmin(servidor, claves, serverKey, idUser);
            f.setVisible(true);
            
        } catch (IOException ex) {
            Logger.getLogger(FrmPrivilegios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmPrivilegios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAplicarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcbActivar;
    private javax.swing.JCheckBox jcbAlta;
    private javax.swing.JCheckBox jcbBaja;
    private javax.swing.JCheckBox jcbMod;
    private javax.swing.JCheckBox jcbPriv;
    // End of variables declaration//GEN-END:variables
}
